server:
  port: 4001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
spring:
  application:
    name: shopping-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rn?useUnicode=true&characterEncoding=utf-8&ServerTimeZone=HongKong
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/wangsen
    #redis:
    #  host: 127.0.0.1
    #  port: 6379
    #  maxIdle: 300
    #  maxActive: 600
    #  maxWait: 1000
    #  testOnBorrow: true
    #  timeout: 1000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mybatis/*.xml

